// <auto-generated />
using System;
using MediaWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MediaWeb.Migrations
{
    [DbContext(typeof(MediaContext))]
    partial class MediaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MediaWeb.Domain.Movie.GenreMovieGenre", b =>
                {
                    b.Property<int>("MovieId");

                    b.Property<int>("MovieGenreId");

                    b.HasKey("MovieId", "MovieGenreId");

                    b.ToTable("GenreMovieCombo");
                });

            modelBuilder.Entity("MediaWeb.Domain.Movie.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Beschrijving");

                    b.Property<byte[]>("Foto");

                    b.Property<int>("Speelduur");

                    b.Property<string>("Titel");

                    b.Property<bool>("Zichtbaar");

                    b.HasKey("Id");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("MediaWeb.Domain.Movie.MovieGenre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naam");

                    b.HasKey("Id");

                    b.ToTable("MovieGenres");
                });

            modelBuilder.Entity("MediaWeb.Domain.Movie.MovieGezienStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Status");

                    b.HasKey("Id");

                    b.ToTable("MovieGezienStatus");
                });

            modelBuilder.Entity("MediaWeb.Domain.Movie.MoviePlaylist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naam");

                    b.HasKey("Id");

                    b.ToTable("MoviePlaylist");
                });

            modelBuilder.Entity("MediaWeb.Domain.Movie.MovieRatingReview", b =>
                {
                    b.Property<int>("MovieId");

                    b.Property<string>("UserId");

                    b.Property<int>("Rating");

                    b.Property<string>("Review");

                    b.Property<bool>("Zichtbaar");

                    b.HasKey("MovieId", "UserId");

                    b.ToTable("MovieRatingReview");
                });

            modelBuilder.Entity("MediaWeb.Domain.Movie.MovieRegisseur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naam");

                    b.HasKey("Id");

                    b.ToTable("MovieRegisseur");
                });

            modelBuilder.Entity("MediaWeb.Domain.Movie.MovieRegisseurCombo", b =>
                {
                    b.Property<int>("MovieId");

                    b.Property<int>("MovieRegisseurId");

                    b.HasKey("MovieId", "MovieRegisseurId");

                    b.ToTable("MovieRegisseurCombo");
                });

            modelBuilder.Entity("MediaWeb.Domain.Movie.UserMovieFav", b =>
                {
                    b.Property<int>("MovieId");

                    b.Property<string>("UserId");

                    b.HasKey("MovieId", "UserId");

                    b.ToTable("UserMovieFav");
                });

            modelBuilder.Entity("MediaWeb.Domain.Movie.UserMovieGezienStatus", b =>
                {
                    b.Property<int>("MovieId");

                    b.Property<string>("UserId");

                    b.Property<int>("MovieGezienStatusId");

                    b.HasKey("MovieId", "UserId");

                    b.ToTable("UserMovieGezienStatus");
                });

            modelBuilder.Entity("MediaWeb.Domain.Movie.UserMoviePlaylist", b =>
                {
                    b.Property<int>("MoviePlaylistId");

                    b.Property<string>("UserId");

                    b.Property<int>("MovieId");

                    b.Property<bool>("Publiek");

                    b.Property<bool>("Zichtbaar");

                    b.HasKey("MoviePlaylistId", "UserId");

                    b.HasIndex("MovieId");

                    b.ToTable("UserMoviePlaylist");
                });

            modelBuilder.Entity("MediaWeb.Domain.Music.GenreMusicGenre", b =>
                {
                    b.Property<int>("MusicId");

                    b.Property<int>("MusicGenreId");

                    b.HasKey("MusicId", "MusicGenreId");

                    b.ToTable("GenreMusicGenre");
                });

            modelBuilder.Entity("MediaWeb.Domain.Music.Music", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("CoverFoto");

                    b.Property<int>("MusicAlbumId");

                    b.Property<int>("MusicArtistId");

                    b.Property<int>("Speelduur");

                    b.Property<bool>("Zichtbaar");

                    b.HasKey("Id");

                    b.HasIndex("MusicAlbumId");

                    b.HasIndex("MusicArtistId");

                    b.ToTable("Music");
                });

            modelBuilder.Entity("MediaWeb.Domain.Music.MusicAlbum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Naam");

                    b.HasKey("Id");

                    b.ToTable("MusicAlbum");
                });

            modelBuilder.Entity("MediaWeb.Domain.Music.MusicArtist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Artist");

                    b.HasKey("Id");

                    b.ToTable("MusicArtist");
                });

            modelBuilder.Entity("MediaWeb.Domain.Music.MusicBeluisterdStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Status");

                    b.HasKey("Id");

                    b.ToTable("MusicBeluisterdStatus");
                });

            modelBuilder.Entity("MediaWeb.Domain.Music.MusicGenre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naam");

                    b.HasKey("Id");

                    b.ToTable("MusicGenre");
                });

            modelBuilder.Entity("MediaWeb.Domain.Music.MusicPlaylist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naam");

                    b.HasKey("Id");

                    b.ToTable("MusicPlaylist");
                });

            modelBuilder.Entity("MediaWeb.Domain.Music.MusicRatingReview", b =>
                {
                    b.Property<int>("MusicId");

                    b.Property<string>("UserId");

                    b.Property<int>("Rating");

                    b.Property<string>("Review");

                    b.Property<bool>("Zichtbaar");

                    b.HasKey("MusicId", "UserId");

                    b.ToTable("MusicRatingReview");
                });

            modelBuilder.Entity("MediaWeb.Domain.Music.UserMusicBesluisterdStatus", b =>
                {
                    b.Property<int>("MusicId");

                    b.Property<string>("UserId");

                    b.Property<int>("MusicBeluisterdId");

                    b.HasKey("MusicId", "UserId");

                    b.ToTable("UserMusicBesluisterdStatus");
                });

            modelBuilder.Entity("MediaWeb.Domain.Music.UserMusicFav", b =>
                {
                    b.Property<int>("MusicId");

                    b.Property<string>("UserId");

                    b.HasKey("MusicId", "UserId");

                    b.ToTable("UserMusicFav");
                });

            modelBuilder.Entity("MediaWeb.Domain.Music.UserMusicPlaylist", b =>
                {
                    b.Property<int>("MusicPlaylistId");

                    b.Property<string>("UserId");

                    b.Property<int>("MusicId");

                    b.Property<bool>("Publiek");

                    b.Property<bool>("Zichtbaar");

                    b.HasKey("MusicPlaylistId", "UserId");

                    b.HasIndex("MusicId");

                    b.ToTable("UserMusicPlaylist");
                });

            modelBuilder.Entity("MediaWeb.Domain.Podcast.Podcast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Datum");

                    b.Property<int>("PodcastMakerId");

                    b.Property<int>("PodcastSerieId");

                    b.Property<int>("Speelduur");

                    b.Property<string>("Titel");

                    b.Property<bool>("Zichtbaar");

                    b.HasKey("Id");

                    b.HasIndex("PodcastMakerId");

                    b.HasIndex("PodcastSerieId");

                    b.ToTable("Podcast");
                });

            modelBuilder.Entity("MediaWeb.Domain.Podcast.PodcastBelsuiterdStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Status");

                    b.HasKey("Id");

                    b.ToTable("PodcastBelsuiterdStatus");
                });

            modelBuilder.Entity("MediaWeb.Domain.Podcast.PodcastMaker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naam");

                    b.HasKey("Id");

                    b.ToTable("PodcastMaker");
                });

            modelBuilder.Entity("MediaWeb.Domain.Podcast.PodcastOnderwerpen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Onderwerp");

                    b.HasKey("Id");

                    b.ToTable("PodcastOnderwerpen");
                });

            modelBuilder.Entity("MediaWeb.Domain.Podcast.PodcastOnderwerpPodcast", b =>
                {
                    b.Property<int>("PodcastId");

                    b.Property<int>("PodcastOnderwerpId");

                    b.HasKey("PodcastId", "PodcastOnderwerpId");

                    b.ToTable("PodcastOnderwerpPodcast");
                });

            modelBuilder.Entity("MediaWeb.Domain.Podcast.PodcastPlaylist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Titel");

                    b.HasKey("Id");

                    b.ToTable("PodcastPlaylist");
                });

            modelBuilder.Entity("MediaWeb.Domain.Podcast.PodcastRatingReview", b =>
                {
                    b.Property<int>("PodcastId");

                    b.Property<string>("UserId");

                    b.Property<int>("Rating");

                    b.Property<string>("Review");

                    b.Property<bool>("Zichtbaar");

                    b.HasKey("PodcastId", "UserId");

                    b.ToTable("PodcastRatingReview");
                });

            modelBuilder.Entity("MediaWeb.Domain.Podcast.PodcastSerie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Titel");

                    b.Property<bool>("Zichtbaar");

                    b.HasKey("Id");

                    b.ToTable("PodcastSerie");
                });

            modelBuilder.Entity("MediaWeb.Domain.Podcast.UserPodcastBeluisterdStatus", b =>
                {
                    b.Property<int>("PodcastId");

                    b.Property<string>("UserId");

                    b.Property<int>("PodcastBeluisterdStatusId");

                    b.HasKey("PodcastId", "UserId");

                    b.ToTable("UserPodcastBelsuiterd");
                });

            modelBuilder.Entity("MediaWeb.Domain.Podcast.UserPodcastFav", b =>
                {
                    b.Property<int>("PodcastId");

                    b.Property<string>("UserId");

                    b.HasKey("PodcastId", "UserId");

                    b.ToTable("UserPodcastFav");
                });

            modelBuilder.Entity("MediaWeb.Domain.Podcast.UserPodcastPlaylist", b =>
                {
                    b.Property<int>("PodcastPlaylistId");

                    b.Property<string>("UserId");

                    b.Property<int>("PodcastId");

                    b.Property<bool>("Publiek");

                    b.Property<bool>("Zichtbaar");

                    b.HasKey("PodcastPlaylistId", "UserId");

                    b.ToTable("UserPodcastPlaylist");
                });

            modelBuilder.Entity("MediaWeb.Domain.Serie.GenreSerieGenre", b =>
                {
                    b.Property<int>("SerieId");

                    b.Property<int>("SerieGenreId");

                    b.HasKey("SerieId", "SerieGenreId");

                    b.ToTable("GenreSerieGenre");
                });

            modelBuilder.Entity("MediaWeb.Domain.Serie.Serie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Beschrijving");

                    b.Property<byte[]>("Foto");

                    b.Property<string>("Titel");

                    b.Property<bool>("Zichtbaar");

                    b.HasKey("Id");

                    b.ToTable("Serie");
                });

            modelBuilder.Entity("MediaWeb.Domain.Serie.SerieGenre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naam");

                    b.Property<int?>("SeriesEpisodesId");

                    b.HasKey("Id");

                    b.HasIndex("SeriesEpisodesId");

                    b.ToTable("SerieGenre");
                });

            modelBuilder.Entity("MediaWeb.Domain.Serie.SerieGezienStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naam");

                    b.HasKey("Id");

                    b.ToTable("SerieGezienStatus");
                });

            modelBuilder.Entity("MediaWeb.Domain.Serie.SerieRatingReview", b =>
                {
                    b.Property<int>("SerieId");

                    b.Property<string>("UserId");

                    b.Property<int>("Rating");

                    b.Property<string>("Review");

                    b.HasKey("SerieId", "UserId");

                    b.ToTable("SerieRatingReview");
                });

            modelBuilder.Entity("MediaWeb.Domain.Serie.SeriesEpisodeRatingReview", b =>
                {
                    b.Property<int>("SeriesEpisodesId");

                    b.Property<string>("UserId");

                    b.Property<int>("Rating");

                    b.Property<string>("Review");

                    b.Property<bool>("Zichtbaar");

                    b.HasKey("SeriesEpisodesId", "UserId");

                    b.ToTable("SeriesEpisodeRatingReview");
                });

            modelBuilder.Entity("MediaWeb.Domain.Serie.SeriesEpisodes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Beschijving");

                    b.Property<int?>("SerieId");

                    b.Property<string>("Titel");

                    b.Property<bool>("Zichtbaar");

                    b.HasKey("Id");

                    b.HasIndex("SerieId");

                    b.ToTable("SeriesEpisodes");
                });

            modelBuilder.Entity("MediaWeb.Domain.Serie.SeriesEpisodesInSeries", b =>
                {
                    b.Property<int>("SerieId");

                    b.Property<int>("SeriesEpisodeId");

                    b.HasKey("SerieId", "SeriesEpisodeId");

                    b.ToTable("SeriesEpisodesInSeries");
                });

            modelBuilder.Entity("MediaWeb.Domain.Serie.SeriesEpisodesPlaylist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Titel");

                    b.HasKey("Id");

                    b.ToTable("SeriesEpisodesPlaylist");
                });

            modelBuilder.Entity("MediaWeb.Domain.Serie.UserSerieGezienStatus", b =>
                {
                    b.Property<int>("SerieGezienStatus");

                    b.Property<string>("UserId");

                    b.Property<int>("SerieId");

                    b.HasKey("SerieGezienStatus", "UserId");

                    b.ToTable("UserSerieGezienStatus");
                });

            modelBuilder.Entity("MediaWeb.Domain.Serie.UserSeriesEpisodesGezienStatus", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<int>("SeriesEpisodeId");

                    b.HasKey("UserId", "SeriesEpisodeId");

                    b.ToTable("UserSeriesEpisodesGezienStatus");
                });

            modelBuilder.Entity("MediaWeb.Domain.Serie.UserSeriesEpisodesPlaylist", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<int>("SeriesEpisodesPlaylistId");

                    b.Property<bool>("Publiek");

                    b.Property<int>("SeriesEpisodeId");

                    b.Property<bool>("Zichtbaar");

                    b.HasKey("UserId", "SeriesEpisodesPlaylistId");

                    b.ToTable("UserSeriesEpisodesPlaylist");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasMaxLength(128);

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("MediaWeb.Domain.Movie.GenreMovieGenre", b =>
                {
                    b.HasOne("MediaWeb.Domain.Movie.Movie")
                        .WithMany("Genres")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MediaWeb.Domain.Movie.MovieRatingReview", b =>
                {
                    b.HasOne("MediaWeb.Domain.Movie.Movie")
                        .WithMany("RatingReviews")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MediaWeb.Domain.Movie.MovieRegisseurCombo", b =>
                {
                    b.HasOne("MediaWeb.Domain.Movie.Movie")
                        .WithMany("Regisseurs")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MediaWeb.Domain.Movie.UserMovieFav", b =>
                {
                    b.HasOne("MediaWeb.Domain.Movie.Movie")
                        .WithMany("UserMovieFav")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MediaWeb.Domain.Movie.UserMovieGezienStatus", b =>
                {
                    b.HasOne("MediaWeb.Domain.Movie.Movie")
                        .WithMany("UserMovieGezienStatus")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MediaWeb.Domain.Movie.UserMoviePlaylist", b =>
                {
                    b.HasOne("MediaWeb.Domain.Movie.Movie")
                        .WithMany("UserMoviePlaylists")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MediaWeb.Domain.Music.GenreMusicGenre", b =>
                {
                    b.HasOne("MediaWeb.Domain.Music.Music")
                        .WithMany("MuziekGenres")
                        .HasForeignKey("MusicId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MediaWeb.Domain.Music.Music", b =>
                {
                    b.HasOne("MediaWeb.Domain.Music.MusicAlbum", "MusicAlbum")
                        .WithMany()
                        .HasForeignKey("MusicAlbumId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MediaWeb.Domain.Music.MusicArtist", "MusicArtist")
                        .WithMany()
                        .HasForeignKey("MusicArtistId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MediaWeb.Domain.Music.MusicRatingReview", b =>
                {
                    b.HasOne("MediaWeb.Domain.Music.Music")
                        .WithMany("MusicRatingReview")
                        .HasForeignKey("MusicId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MediaWeb.Domain.Music.UserMusicBesluisterdStatus", b =>
                {
                    b.HasOne("MediaWeb.Domain.Music.Music")
                        .WithMany("UserMusicBeluisterdStatus")
                        .HasForeignKey("MusicId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MediaWeb.Domain.Music.UserMusicFav", b =>
                {
                    b.HasOne("MediaWeb.Domain.Music.Music")
                        .WithMany("UserMusicFavs")
                        .HasForeignKey("MusicId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MediaWeb.Domain.Music.UserMusicPlaylist", b =>
                {
                    b.HasOne("MediaWeb.Domain.Music.Music")
                        .WithMany("UserMusicPlaylists")
                        .HasForeignKey("MusicId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MediaWeb.Domain.Podcast.Podcast", b =>
                {
                    b.HasOne("MediaWeb.Domain.Podcast.PodcastMaker", "PodcastMaker")
                        .WithMany()
                        .HasForeignKey("PodcastMakerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MediaWeb.Domain.Podcast.PodcastSerie", "PostcastSerie")
                        .WithMany("Podcasts")
                        .HasForeignKey("PodcastSerieId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MediaWeb.Domain.Podcast.PodcastOnderwerpPodcast", b =>
                {
                    b.HasOne("MediaWeb.Domain.Podcast.Podcast")
                        .WithMany("Onderwerpen")
                        .HasForeignKey("PodcastId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MediaWeb.Domain.Serie.GenreSerieGenre", b =>
                {
                    b.HasOne("MediaWeb.Domain.Serie.Serie")
                        .WithMany("SerieGenres")
                        .HasForeignKey("SerieId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MediaWeb.Domain.Serie.SerieGenre", b =>
                {
                    b.HasOne("MediaWeb.Domain.Serie.SeriesEpisodes")
                        .WithMany("SerieGenre")
                        .HasForeignKey("SeriesEpisodesId");
                });

            modelBuilder.Entity("MediaWeb.Domain.Serie.SerieRatingReview", b =>
                {
                    b.HasOne("MediaWeb.Domain.Serie.Serie")
                        .WithMany("SerieRatingReview")
                        .HasForeignKey("SerieId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MediaWeb.Domain.Serie.SeriesEpisodes", b =>
                {
                    b.HasOne("MediaWeb.Domain.Serie.Serie")
                        .WithMany("SeriesEpisodes")
                        .HasForeignKey("SerieId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
